# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev6+gaa24f8f.d20230502"
__version_tuple__ = version_tuple = (0, 1, "dev6", "gaa24f8f.d20230502")
